### ISSUE TITLE
DevOps: Integración continua

### ISSUE THREAD

**Issue by adamantike** [yesdoc/debtrack#2]
# Introducción
Una herramienta de **integración continua** nos permite llevar a cabo integraciones automáticas (compilación y ejecución de tests) del código para poder detectar errores antes de que los cambios pasen a formar parte de la rama de trabajo principal del proyecto.

En nuestro caso, nos permitirá controlar cada PR antes de que ésta sea aceptada e integrada.

# Herramientas
* [CircleCI](https://circleci.com/)
* [Codeship](https://codeship.com/)
* [drone.io](https://drone.io/)
* [Shippable](http://www.shippable.com/)
* [Travis CI](https://travis-ci.com/)

# Comparación
Característica | CircleCI | Codeship | drone.io | Shippable | Travis CI
----------------- | :---------: | :----------: | :---------: | :-----------: | :----------:
Integración con GitHub    | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark:
Integración con Bitbucket    | :x: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :x:
Plan gratuito para repositorios públicos    | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark:
Plan gratuito para repositorios privados    | :white_check_mark: | :five: | :x: | :white_check_mark: | :x:
Cantidad de compilaciones concurrentes    | :one: | :one: | :one: | :one: | :one:
Soporte de Python 2    | :white_check_mark: | :white_check_mark: | :white_check_mark: (Beta) | :white_check_mark: | :white_check_mark:
Soporte de Python 3    | :white_check_mark: | :white_check_mark: | :white_check_mark: (Beta) | :white_check_mark: | :white_check_mark:

# Elección
![Shippable](https://www.shippable.com/images/logos/shippable_logo_full-blue.png)

**Comment by coco19** [comment]
En la wikipedia sale que shippable es propietario??esto es así? [comparación software de integración continua](https://en.wikipedia.org/wiki/Continuous_integration)
